- name: Include blackbox exporter variables
  include_vars: 'blackboxexporter.yml'

- name: Creating blackbox exporter directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    mode: 0750
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_blackbox_exporter_config_dir }}"

- name: Download and extract Prometheus blackbox_exporter tarball
  unarchive:
    src: "{{ prometheus_blackbox_exporter_tarball_url }}"
    dest: "{{ prometheus_install_dir }}"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
    copy: no
    creates: "{{ prometheus_install_dir }}/{{ prometheus_blackbox_exporter_archive }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy blackbox exporter config
  template:
    src: blackbox.yml.j2
    dest: "{{ prometheus_blackbox_exporter_config_dir }}/blackbox.yml"
    owner: "{{ prometheus_owner }}"
    group: "{{ prometheus_group }}"
  notify:
    - reload blackboxexporter

- name: Apply elevated privileges to blackbox_exporter for ICMP probe
  capabilities:
    path: "{{ prometheus_install_dir }}/{{ prometheus_blackbox_exporter_archive }}/blackbox_exporter"
    capability: cap_net_raw+ep
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - reload blackboxexporter

- name: Install Prometheus blackbox exporter systemd service
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackboxexporter.service
  notify:
    - reload daemon
    - restart blackboxexporter
